spring:
  application:
    name: projecttasker
  datasource:
    url: jdbc:mysql://localhost:3306/projecttasker
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}